/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.myproject.lms;

import java.util.Scanner;

public class App {
  public static void main(String[] args) {
    
    Scanner keyboard = new Scanner(System.in);
    
    System.out.print("도서명? ");
    String title = keyboard.nextLine();
    
    System.out.print("지은이? ");
    String author = keyboard.nextLine();
    
    System.out.print("출판사? ");
    String publisher = keyboard.nextLine();
    
    System.out.print("카테고리? ");
    String categories = keyboard.nextLine();
    
    System.out.print("출판 년도? ");
    int publishYear = keyboard.nextInt();
    
    System.out.println("--------결과--------");
    
    keyboard.close();
    
    System.out.printf("도서명 : %s\n", title);
    System.out.printf("지은이 : %s\n", author);
    System.out.printf("출판사 : %s\n", publisher);
    System.out.printf("카테고리 : %s\n", categories);
    System.out.printf("출판 년도: %d 년도", publishYear);
    
    
    
    

  }
}
