/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.myproject.lms;

import java.util.Scanner;

public class App {
  public static void main(String[] args) {
    
    Scanner keyboard = new Scanner(System.in);
    
    System.out.print("번호? ");
    String number = keyboard.nextLine();
    
    System.out.print("수업명? ");
    String title =  keyboard.nextLine();
    
    System.out.print("수업내용? ");
    String description = keyboard.nextLine();
    
    System.out.print("시작일? ");
    String startDate =  keyboard.nextLine();
    
    System.out.print("종료일? ");
    String endDate =  keyboard.nextLine();
    
    System.out.print("총수업시간? ");
    String totalHours =  keyboard.nextLine();
    
    System.out.print("일수업시간? ");
    String dayHours =  keyboard.nextLine();
    
    System.out.println("-------------");
    
    System.out.printf("번호: %s\n", number);
    System.out.printf("수업명: %s\n", title);
    System.out.printf("수업내용: %s\n", description);
    System.out.printf("기간: %s ~ %s\n", startDate, endDate);
    System.out.printf("총수업시간: %s\n", totalHours);
    System.out.printf("일수업시간: %s\n", dayHours);
    
    keyboard.close();

  }
}
